services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: rootpassword
     MYSQL_DATABASE: my_app_db
     MYSQL_USER: myuser
     MYSQL_PASSWORD: Project123$
    ports:
      - "3306:3306"

  nodeapp:
    build: .
    container_name: node-app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: myuser
      DB_PASSWORD: Project123$
      DB_NAME: my_app_db
      JWT_SECRET: supersecretkey
      JWT_EXPIRES_IN: 1h
    ports:
      - "3000:3000"
